config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  get 'pages/about'

  get 'pages/contact'
  get 'seller' => "listings#seller"

root 'listings#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :image, ImageUploader
    
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_presence_of :image
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
   validates_presence_of :name
  
 # validates :name, presence: true
  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   # devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  #def configure_devise_permitted_parameters
   # registration_params = [:name, :email, :password, :password_confirmation]

   # if params[:action] == 'update'
    #  devise_parameter_sanitizer.for(:account_update) { 
     #   |u| u.permit(registration_params << :current_password)
     # }
   #elsif params[:action] == 'create'
     # devise_parameter_sanitizer.for(:sign_up) { 
     #   |u| u.permit(registration_params) 
     # }
   # end
 # end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/listings_helper.rb
module ListingsHelper
   
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-full navbar-dark bg-inverse">

  <a class="navbar-brand" href="/">Buy My Stuff</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to "About", pages_about_path %></a>
    </li>
    <li class="nav-item">
     <a class="nav-link" <%= link_to "Contact", pages_contact_path %></a>
    </li>
      <% if user_signed_in? %>
      <li class="nav-item"><a class="nav-link" <%= link_to "Manage Listings", seller_path %></a></li>
       <li class="nav-item"><a class="nav-link" <%= link_to "Edit Profile", edit_user_registration_path %></a></li>
      <li class="nav-item"><a class="nav-link pull-right" <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a></li>
       
      <% else %>
      <li class="nav-item"><a class="nav-link"<%= link_to "Sign Up", new_user_registration_path %></a></li>
      <li class="nav-item"><a class="nav-link"<%= link_to "Sign In", new_user_session_path %></a></li>
      <% end %>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
  <%= yield %>
  </div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
        <ul>
          
        <% @listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :name %></br>
      <%= f.text_field :name, class:"form-control", placeholder:"Enter item name." %>
    </div>
  
    <div class="form-group">
      <%= f.label :description %></br>
      <%= f.text_area :description, class:"form-control", placeholder:"Enter description of item." %>
    </div>
  
    <div class="form-group">
      <%= f.label :price %></br>
      <%= f.text_field :price, class:"form-control", placeholder:"Enter price of item." %>
    </div>
    
   <div class="form-group">
      <%= f.label :image %></br>
      <%= f.file_field :image, class:"form-control" %>
    </div>
    
    <div class="form-group"></br>
      <%= f.submit class:"btn btn-success" %>
     </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class:'btn btn-link' %> |
<%= link_to 'Back', listings_path, class:'btn btn-link' %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

  
    <div class="row">
    <% @listings.each do |listing| %>
        <div class="col-md-3">
          <%= image_tag listing.image_url(:thumb) %>
          <div class="caption">
            <h3><%= listing.name %></h3>
          <p><%= number_to_currency(listing.price) %></p>
          <p><%= listing.user.name %></p>
        
        <%= link_to 'Show', listing, class:'btn btn-link' %>
        <%= link_to 'Edit', edit_listing_path(listing), class:'btn btn-link' %>
        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-link' %>
      </div>
      </div>
    <% end %>
    </div>

<br>

<%= link_to 'New Listing', new_listing_path, class:'btn btn-link' %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

  
    <div class="row">
    <% @listings.each do |listing| %>
        <div class="col-md-3">
          <%= image_tag listing.image_url(:thumb) %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= listing.user.name %></p>
            <% if (user_signed_in?) && (current_user == listing.user) %>
            <%= link_to "Edit", edit_listing_path(listing), class: 'btn btn-link' %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-link' %>
            <%= link_to 'Show', listing, class:'btn btn-link' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

 <br>

<% if (user_signed_in?) %>

<%= link_to 'New Listing', new_listing_path, class:'btn btn-link' %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-8"><%= image_tag @listing.image_url %></div>
  <div class="col-md-4">
    <h3><strong><%= @listing.name %></strong></h3>
    <p><strong><%= @listing.description %></strong>
    <p><%= number_to_currency @listing.price %></p></p>
  </div>
</div>


<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing), class:'btn btn-link' %> |
<% end %>
<%= link_to 'Back', listings_path, class:'btn btn-link' %>

app/views/pages/about.html.erb
<h1>Buy Everything!!</h1>
<p>Yes, you need everything here.</p>

app/views/pages/contact.html.erb
<h1>Email me at gerbermichelle23@gmail.com</h1>

<p>We can be email pals!</p>